### ISSUE TITLE
Add inserion sort 

### ISSUE THREAD

**Issue by vishichoudhary** [vishichoudhary/Algos#10]

**Comment by vishichoudhary** [comment]
@aakankshaprasad Can you do it?

**Comment by aakankshaprasad** [comment]
Yes I'm doing it

**Comment by vishichoudhary** [comment]
Ok waiting for your pr

**Comment by aakankshaprasad** [comment]
Kindly approve, I'm fast enough ?

**Comment by vishichoudhary** [comment]
@aakankshaprasad kindly check your gmail a email has been sent to you regarding issues
